dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - requests
    - scrapy
    - pillow
    - twisted
    - pygame
    - pyglet
    - nose
    - ipython
    - scapy
